# Copyright 2022 The kpt and Nephio Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

functions:
  - function: set-image
    images:
      - ghcr.io/kptdev/krm-functions-catalog/set-image@sha256:d07677591e5b39a56d44bafaba0d881e4f2ae25ed020dfa2ad002fb9e62d1508
      - ghcr.io/kptdev/krm-functions-catalog/set-image:v0.1.0
  - function: set-namespace
    images:
      - ghcr.io/kptdev/krm-functions-catalog/set-namespace@sha256:7adc23986f97572d75af9aec6a7f74d60f7b9976227f43a75486633e7c539e6f
      - ghcr.io/kptdev/krm-functions-catalog/set-namespace:v0.2.0
  - function: set-namespace-v3
    images:
      - ghcr.io/kptdev/krm-functions-catalog/set-namespace@sha256:0ec0fb2380be42142a87a7c9815f0d30415e2da07468591dd9345c7c81d6c93e
      - ghcr.io/kptdev/krm-functions-catalog/set-namespace:v0.3.4
  - function: upsert-resource
    images:
      - ghcr.io/kptdev/krm-functions-catalog/upsert-resource@sha256:77196bdb9e33e4259d530ee1996a05c40bbefe39b80d52dcb66c32f7b85a62f1
      - ghcr.io/kptdev/krm-functions-catalog/upsert-resource:v0.2.0
  - function: set-project-id
    images:
      - ghcr.io/kptdev/krm-functions-catalog/set-project-id@sha256:966c9e51163bce52274dfa0406ae580283712cb38625660cd2f66e9f13d2c01b
      - ghcr.io/kptdev/krm-functions-catalog/set-project-id:v0.2.0
  - function: apply-setters
    images:
      - ghcr.io/kptdev/krm-functions-catalog/apply-setters@sha256:4d4295727183396f0c3c6a75d2560254c2f9041a39e95dc1e5beffeb49cc1a12
      - ghcr.io/kptdev/krm-functions-catalog/apply-setters:v0.2.0
  - function: apply-setters-v1
    images:
      - ghcr.io/kptdev/krm-functions-catalog/apply-setters@sha256:d2a0219b24a47ebb4bf568d3ccf5bb0e7be2f3f94b28b0c3b1bed011a51d7c35
      - ghcr.io/kptdev/krm-functions-catalog/apply-setters:v0.1
      - ghcr.io/kptdev/krm-functions-catalog/apply-setters:v0.1.1
  - function: search-replace
    images:
      - ghcr.io/kptdev/krm-functions-catalog/search-replace@sha256:6864b06bf654fbdff3efb666a0a75fa14da2ba405f33187b60648e0b74bc2272
      - ghcr.io/kptdev/krm-functions-catalog/search-replace:v0.2.0
  - function: ensure-name-substring
    images:
      - ghcr.io/kptdev/krm-functions-catalog/ensure-name-substring@sha256:3105ac150f86dcafa2d656e30feb5c51b83a43f5bb9b84458cdde620c9757227
      - ghcr.io/kptdev/krm-functions-catalog/ensure-name-substring:v0.1.1
  - function: set-annotations
    images:
      - ghcr.io/kptdev/krm-functions-catalog/set-annotations@sha256:76d65ebddf6ce9c2c00bbcb3c0e963a2d856685bdcf2f1072386f41ca9b563e5
      - ghcr.io/kptdev/krm-functions-catalog/set-annotations:v0.1.4
  - function: set-labels
    images:
      - ghcr.io/kptdev/krm-functions-catalog/set-labels@sha256:0dfc3c8aba8b791d0c45fe7eafbc8cf3c5920a09f69848f46dcc270ae3423641
      - ghcr.io/kptdev/krm-functions-catalog/set-labels:v0.1.5
  - function: starlark
    images:
      - ghcr.io/kptdev/krm-functions-catalog/starlark@sha256:c347e28606fa1a608e8e02e03541a5a46e4a0152005df4a11e44f6c4ab1edd9a
      - ghcr.io/kptdev/krm-functions-catalog/starlark:v0.3.0
