name: Dev Image Build & Push

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "release/**"
      - "OWNERS"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "release/**"
      - "OWNERS"
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Force rebuild without cache'
        required: false
        default: false
        type: boolean

env:
  REGISTRY: ${{ github.event_name == 'pull_request' && 'ghcr.io' || 'docker.io' }}
  ORG: ${{ github.event_name == 'pull_request' && github.repository || 'nephio' }}

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-image:
    if: github.repository_owner == 'nephio-project'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./build/Dockerfile
            image: ${{ github.event_name == 'pull_request' && 'ghcr.io' || 'docker.io' }}/${{ github.event_name == 'pull_request' && github.repository || 'nephio' }}/porch-server
          - dockerfile: ./controllers/Dockerfile
            image: ${{ github.event_name == 'pull_request' && 'ghcr.io' || 'docker.io' }}/${{ github.event_name == 'pull_request' && github.repository || 'nephio' }}/porch-controllers
          - dockerfile: ./func/Dockerfile
            image: ${{ github.event_name == 'pull_request' && 'ghcr.io' || 'docker.io' }}/${{ github.event_name == 'pull_request' && github.repository || 'nephio' }}/porch-function-runner
          - dockerfile: ./func/Dockerfile-wrapperserver
            image: ${{ github.event_name == 'pull_request' && 'ghcr.io' || 'docker.io' }}/${{ github.event_name == 'pull_request' && github.repository || 'nephio' }}/porch-wrapper-server


    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Log in to the Container registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.event_name == 'pull_request' && github.actor || vars.DOCKERHUB_USERNAME }}
          password: ${{ github.event_name == 'pull_request' && secrets.GITHUB_TOKEN || secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          images: ${{ matrix.image }}
          tags: |
            type=sha

      - name: Build and push Docker images
        uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 # v6.7.0
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ matrix.image }}:${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || (github.ref_name == 'main' && 'latest' || github.ref_name) }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          no-cache: ${{ inputs.force_rebuild || false }}
          sbom: true
